# Generated by Django 2.0.3 on 2018-03-29 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion', models.FloatField()),
                ('formato', models.CharField(max_length=6)),
                ('emocion', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desactivo', 'Desactivo')], default='Desactivo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desactivo', 'Desactivo')], default='Desactivo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_diarias', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='1', max_length=20)),
                ('sede', models.CharField(choices=[('Mayorca', 'Mayorca'), ('Laureles', 'Laureles'), ('Poblado', 'Poblado')], default='Poblado', max_length=20)),
                ('horario', models.CharField(max_length=200)),
                ('idioma', models.CharField(choices=[('Ingles', 'Ingles'), ('Espanol', 'Espanol'), ('Portugues', 'Portugues'), ('Mandarin', 'Mandarin')], default='Ingles', max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Docente')),
                ('intensidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workClass.Intensidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion', models.FloatField()),
                ('formato', models.CharField(max_length=6)),
                ('emocion', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=200)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Sesion')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Sesion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workClass.Estudiante'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workClass.Sesion'),
        ),
        migrations.AddField(
            model_name='audio',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Sesion'),
        ),
    ]
