# Generated by Django 2.0.3 on 2018-03-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='ruta',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='ruta',
            field=models.FileField(upload_to=''),
        ),
    ]
