# Generated by Django 2.0.5 on 2018-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
