# Generated by Django 2.0.4 on 2018-04-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0002_auto_20180329_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='intensidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workClass.Intensidad'),
        ),
    ]
