# Generated by Django 2.0.4 on 2018-05-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0002_auto_20180415_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='emocion',
            name='audio',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
