# Generated by Django 2.0.4 on 2018-05-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0003_auto_20180511_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duracion',
        ),
    ]
