# Generated by Django 2.0.4 on 2018-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0004_remove_video_duracion'),
    ]

    operations = [

    ]
