# Generated by Django 2.0.4 on 2018-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workClass', '0006_auto_20180521_0231'),
    ]

    operations = [


        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.DateField(),
        ),

    ]
